name: base
channels:
    - conda-forge
    - bioconda
dependencies:
    - igv
    - xorg-libxtst
    - openssl < 3.0.0
    - r >= 4.2
    - r-tidyverse
    - r-docopt
    - r-devtools
    - r-abind
    - r-cowplot
    - r-gridextra
    - r-flextable
    - r-ggplotify
    - r-officer
    - r-png
    - r-jpeg
    - r-kinship2
    - r-gdtools
    - bioconductor-seqvartools
    - bioconductor-genomicranges
    - bioconductor-rtracklayer